// keeping these defaults in a separate file since it takes so many lines

export class RomConstants {

    constructor() { }

    constants = {
        BPRE0: {
          FREE_SPACE_START: 0x71A23C,
      
          MONSTER_COUNT: 412,
          MONSTER_NAMES_ADDRESS: 0x144,
          MONSTER_BASE_STATS_ADDRESS: 0x156C28,
          ABILITY_NAMES_ADDRESS: 0x24FC40,
          ABILITY_COUNT: 78,
          MOVE_NAMES_ADDRESS: 0x148,
          MOVE_COUNT: 355,
          MONSTER_FRONT_PIXEL_ADDRESS: 0x128,
          MONSTER_BACK_PIXEL_ADDRESS: 0x12C,
          MONSTER_NORMAL_PALETTE_ADDRESS: 0x130,
          MONSTER_SHINY_PALETTE_ADDRESS: 0x134,
          MONSTER_ICON_PIXEL_ADDRESS: 0x3D37A0,
          MONSTER_ICON_PALETTE_ADDRESS: 0x3D3E80,
          MONSTER_ICON_PALETTES: 0x3D3740,
          MONSTER_ICON_PALETTE_COUNT: 3,
      
          ITEM_COUNT: 375,
          ITEM_DATA_ADDRESS: 0x3DB028,
          ITEM_BITMAPS_ADDRESS: 0x3D4294,
      
          MAP_ENCOUNTER_TABLE: 0x82990,
          MAP_NAME_OFFSET: -88,
          MAP_NAMES_ADDRESS: 0x3EECFC,
          MAP_NAMES_COUNT: 109,
          MAP_BANK_ADDRESS: 0x3526A8,
          MAP_BANK_COUNT: 43,
          MAP_BANK_SIZES: [5,123,60,66,4,6,8,10,6,8,20,10,8,2,10,4,2,2,2,1,1,2,2,3,2,3,2,1,1,1,1,7,5,5,8,8,5,5,1,1,1,2,1],
          BLOCK_BIT_SIZE: 16,
          MAIN_TILESET_BLOCK_COUNT: 640,
          MAIN_TILESET_PALETTE_COUNT: 7,
      
          MAP_TILESET_BASE: 0x2D4A94,
          MAP_TILESET_ANIMATION_FLAG: 0x68014809,
          MAP_TILESET_ANIMATION_HEADER: 0x2D4AA4,
          MAP_SPRITES_ADDRESS: 0x39FDB0,
          MAP_SPRITES_PALETTES: 0x3A5158,
          MAP_DOORS_ADDRESS: 0x35B5D8,
          MAP_DOOR_PIXEL_LENGTH: 128,
          DEFAULT_MAP: '3.0',
      
          // Credits to maierfelix for the structure
          FIELD_OVERLAY_HEADER_ADDRESS: 0x3A000C + 4,
          FIELD_OVERLAY_META: [
            { index: 0, tilemapWidth: 80,  tilemapHeight: 16, label: 'Shadow (small)', paletteOverrideId: 2 },
            { index: 1, tilemapWidth: 80,  tilemapHeight: 16, label: 'Shadow (medium)', paletteOverrideId: 2 },
            { index: 2, tilemapWidth: 80,  tilemapHeight: 16, label: 'Shadow (large)', paletteOverrideId: 2 },
            { index: 3, tilemapWidth: 128,  tilemapHeight: 16, label: 'Shadow (extra large)', paletteOverrideId: 2 },
            { index: 4, tilemapWidth: 16,  tilemapHeight: 80, label: 'Tall Grass' },
            { index: 5, tilemapWidth: 16, tilemapHeight: 80, label: 'Ripple' },
            { index: 6, tilemapWidth: 16, tilemapHeight: 80, label: 'Ash' },
            { index: 7, tilemapWidth: 32, tilemapHeight: 96, label: 'Surf Blob' },
            { index: 8, tilemapWidth: 16, tilemapHeight: 64 * 2, label: 'Arrow' },
            { index: 9, tilemapWidth: 16, tilemapHeight: 24, label: 'Ground Impact Dust' },
            { index: 10, tilemapWidth: 16, tilemapHeight: 32, label: 'Jump Tall Grass' },
            { index: 11, tilemapWidth: 16, tilemapHeight: 32, label: 'Sand Footprints' },
            { index: 12, tilemapWidth: 16, tilemapHeight: 64, label: 'Jump Big Splash' },
            { index: 13, tilemapWidth: 16, tilemapHeight: 16, label: 'Splash' },
            { index: 14, tilemapWidth: 16, tilemapHeight: 32, label: 'Jump Small Splash' },
            { index: 15, tilemapWidth: 16, tilemapHeight: 64, label: 'Long Grass' },
            { index: 16, tilemapWidth: 16, tilemapHeight: 80, label: 'Jump Long Grass' },
            { index: 17, tilemapWidth: 16, tilemapHeight: 144, label: 'Unused Grass 1' },
            { index: 18, tilemapWidth: 16, tilemapHeight: 64, label: 'Unused Grass 2' },
            { index: 19, tilemapWidth: 16, tilemapHeight: 64, label: 'Unused Sand' },
            { index: 20, tilemapWidth: 16, tilemapHeight: 80, label: 'Water Surfacing' },
            // { index: 21, tilemapWidth: 16, tilemapHeight: 80, label: 'Reflection Distortion' },
            // { index: 22, tilemapWidth: 16, tilemapHeight: 96, label: 'Sparkle' },
            { index: 23, tilemapWidth: 16, tilemapHeight: 32, label: 'Deep Sand Footprints' },
            { index: 24, tilemapWidth: 16, tilemapHeight: 224, label: 'Tree Disguise', paletteOverrideId: 2 },
            { index: 25, tilemapWidth: 16, tilemapHeight: 224, label: 'Mountain Disguise', paletteOverrideId: 3 },
            { index: 26, tilemapWidth: 64, tilemapHeight: 64 * 5, label: 'Bird' },
            { index: 27, tilemapWidth: 16, tilemapHeight: 64, label: 'Bike Tire Tracks' },
            { index: 28, tilemapWidth: 16, tilemapHeight: 224, label: 'Sand Disguise', paletteOverrideId: 4 },
            { index: 29, tilemapWidth: 16, tilemapHeight: 32, label: 'Sand Pile' },
            { index: 30, tilemapWidth: 16, tilemapHeight: 16, label: 'Short Grass', paletteOverrideId: 2 },
            { index: 31, tilemapWidth: 16, tilemapHeight: 16, label: 'Hot Springs Water' },
            // { index: 32, tilemapWidth: 16, tilemapHeight: 224, label: 'Ash Puff' },
            // { index: 33, tilemapWidth: 16, tilemapHeight: 224, label: 'Ash Launch' },
            { index: 34, tilemapWidth: 16, tilemapHeight: 224, label: 'Bubbles' },
            // { index: 35, tilemapWidth: 16, tilemapHeight: 32, label: 'Small Sparkle' },
            // { index: 36, tilemapWidth: 64, tilemapHeight: 384, label: 'Rayquaza', paletteOverrideId: 2 }
          ], 
          FIELD_OVERLAY_BASE_OAM_ADDRESS: 0x3a36e0,
          FIELD_OVERLAY_PALETTES: [
            { key: 0xFFFF, address: 0x35B968 },
            { key: 0x1004, address: 0x398fA8 },
            { key: 0x1005, address: 0x398fC8 }
          ],
          GRASS_OVERLAY_PIXEL_ADDRESS: 0x39a048,
          GRASS_OVERLAY_PALETTE_ADDRESS: 0x398FC8,
      
          MUSIC_MODIFIER: 261,
          MUSIC_NAMES: ["Healing (RS)", "Level Up", "Evolution Start", "Evolution/Safari", "Battle 1", "Battle 2", "???", "Fanfare 1", "Fanfare 2", "You Fail It!", "You Fail It Again!", "Follow Me", "Game Corner", "Evil Lurks", "Gym", "Jigglypuff's Song", "Introduction", "Pokemon Theme", "Cinnabar Island", "Lavender Town", "Healing", "Bicycle", "Encounter 1", "Encounter 2", "Encounter 3", "You're In The Hall of Fame!", "Viridian Forest", "Mount Moon", "Abandoned Place", "End Credits", "Route Theme 1", "Route Theme 2/Intro", "Route Theme 3", "Route Theme 4", "Indigo Plateau", "Battle 3", "Battle 4", "Battle 5", "Battle 6", "Pallet Town", "Oak's Lab", "Oak's Theme", "Pokemon Center", "SS Anne", "Surf's Up", "Pokemon Tower", "Silph Co.", "Cerulean City", "Celadon City", "Victory 1", "Victory 2", "Victory 3", "Vermillion City", "Viridian City/Pewter City", "Gary's Theme", "Gary's Theme (bis)", "Fanfare 3", "Fanfare 4", "You caught a Pokemon!", "Trainer Card Photo", "Gamefreak", "Victory 2 (bis)", "Intro Message 1", "Intro Message 2", "Intro Message 3", "Game Corner (+1)", "Game Corner (+2)", "Net Corner", "Mystery Connection", "Game Corner (+3)", "Mount Ember", "Follow Me (alt)", "Water Labyrinth", "Tanoby Ruins", "Islands 1-3", "Islands 4-5", "Islands 6-7(AKA Violet City Theme from GSC)", "PokeFlute", "Battle - Deoxys", "Battle 5 (+1)", "Battle 5 (+2)", "Encounter 4", "Deoxys Encounter", "Trainer Tower", "Pallet Town (fame mix)", "Teachy TV"],
      
          STARTER_MONSTERS_ADDRESS: 0x457104,
          START_BANK_ID_ADDRESS: 0x054A04,
          START_MAP_ID_ADDRESS: 0x054A06,
          START_TILE_X_ADDRESS: 0x054A08,
          START_TILE_Y_ADDRESS: 0x054A00,
      
          BATTLE_BACKGROUNDS_ADDRESS: 0x24EE34,
          BATTLE_BACKGROUNDS_COUNT: 20,
      
          TRAINER_DATA_ADDRESS: 0x23EAF0,
          TRAINER_COUNT: 742,
          TRAINER_SPRITE_COUNT: 148,
          TRAINER_BITMAPS_ADDRESS: 0x23957C,
          TRAINER_PALETTES_ADDRESS: 0x239A1C,
          TRAINER_CLASS_NAMES: 0xD80A0,
          TRAINER_CLASS_COUNT: 107
        },
        // BPRE1: {
        //   FREE_SPACE_START: 0x71A29C,
      
        //   MONSTER_COUNT: 412,
        //   MONSTER_NAMES_ADDRESS: 0x144,
        //   MONSTER_BASE_STATS_ADDRESS: 0x156CA0,
        //   ABILITY_NAMES_ADDRESS: 0x24FCB0,
        //   ABILITY_COUNT: 78,
        //   MOVE_NAMES_ADDRESS: 0x148,
        //   MOVE_COUNT: 355,
        //   MONSTER_FRONT_PIXEL_ADDRESS: 0x128,
        //   MONSTER_BACK_PIXEL_ADDRESS: 0x12C,
        //   MONSTER_NORMAL_PALETTE_ADDRESS: 0x130,
        //   MONSTER_SHINY_PALETTE_ADDRESS: 0x134,
        //   MONSTER_ICON_PIXEL_ADDRESS: 0x3D37A0,
        //   MONSTER_ICON_PALETTE_ADDRESS: 0x3D3E80,
        //   MONSTER_ICON_PALETTES: 0x3D3740,
        //   MONSTER_ICON_PALETTE_COUNT: 3,
      
        //   STARTER_MONSTERS_ADDRESS: 0x457164,
        //   START_BANK_ID_ADDRESS: 0x054A18,
        //   START_MAP_ID_ADDRESS: 0x054A1A,
        //   START_TILE_X_ADDRESS: 0x054A1C,
        //   START_TILE_Y_ADDRESS: 0x054A14,
      
        //   ITEM_COUNT: 375,
        //   ITEM_DATA_ADDRESS: 0x3DB098,
        //   ITEM_BITMAPS_ADDRESS: 0x3D4304,
      
        //   MAP_ENCOUNTER_TABLE: 0x829A4,
        //   MAP_NAME_OFFSET: -88,
        //   MAP_NAMES_ADDRESS: 0x3EED6C,
        //   MAP_NAMES_COUNT: 109,
        //   MAP_BANK_ADDRESS: 0x352718,
        //   MAP_BANK_COUNT: 43,
        //   MAP_BANK_SIZES: [5,123,60,66,4,6,8,10,6,8,20,10,8,2,10,4,2,2,2,1,1,2,2,3,2,3,2,1,1,1,1,7,5,5,8,8,5,5,1,1,1,2,1],
        //   BLOCK_BIT_SIZE: 16,
        //   MAIN_TILESET_BLOCK_COUNT: 640,
        //   MAIN_TILESET_PALETTE_COUNT: 7,
      
        //   MAP_TILESET_BASE: 0x2D4B04,
        //   MAP_TILESET_ANIMATION_FLAG: 0x68014809,
        //   MAP_TILESET_ANIMATION_HEADER: 0x2D4B14,
        //   MAP_SPRITES_ADDRESS: 0x39FDB0,
        //   MAP_SPRITES_PALETTES: 0x3A5158,
        //   MAP_DOORS_ADDRESS: 0x35B5D8,
        //   MAP_DOOR_PIXEL_LENGTH: 128,
        //   DEFAULT_MAP: '3.0',
          
        //   FIELD_OVERLAY_HEADER_ADDRESS: 0x3A000C,
        //   GRASS_OVERLAY_PIXEL_ADDRESS: 0x39A0B8,
        //   GRASS_OVERLAY_PALETTE_ADDRESS: 0x399038,
      
        //   MUSIC_MODIFIER: 261,
        //   MUSIC_NAMES: ["Healing (RS)", "Level Up", "Evolution Start", "Evolution/Safari", "Battle 1", "Battle 2", "???", "Fanfare 1", "Fanfare 2", "You Fail It!", "You Fail It Again!", "Follow Me", "Game Corner", "Evil Lurks", "Gym", "Jigglypuff's Song", "Introduction", "Pokemon Theme", "Cinnabar Island", "Lavender Town", "Healing", "Bicycle", "Encounter 1", "Encounter 2", "Encounter 3", "You're In The Hall of Fame!", "Viridian Forest", "Mount Moon", "Abandoned Place", "End Credits", "Route Theme 1", "Route Theme 2/Intro", "Route Theme 3", "Route Theme 4", "Indigo Plateau", "Battle 3", "Battle 4", "Battle 5", "Battle 6", "Pallet Town", "Oak's Lab", "Oak's Theme", "Pokemon Center", "SS Anne", "Surf's Up", "Pokemon Tower", "Silph Co.", "Cerulean City", "Celadon City", "Victory 1", "Victory 2", "Victory 3", "Vermillion City", "Viridian City/Pewter City", "Gary's Theme", "Gary's Theme (bis)", "Fanfare 3", "Fanfare 4", "You caught a Pokemon!", "Trainer Card Photo", "Gamefreak", "Victory 2 (bis)", "Intro Message 1", "Intro Message 2", "Intro Message 3", "Game Corner (+1)", "Game Corner (+2)", "Net Corner", "Mystery Connection", "Game Corner (+3)", "Mount Ember", "Follow Me (alt)", "Water Labyrinth", "Tanoby Ruins", "Islands 1-3", "Islands 4-5", "Islands 6-7(AKA Violet City Theme from GSC)", "PokeFlute", "Battle - Deoxys", "Battle 5 (+1)", "Battle 5 (+2)", "Encounter 4", "Deoxys Encounter", "Trainer Tower", "Pallet Town (fame mix)", "Teachy TV"],
      
        //   BATTLE_BACKGROUNDS_ADDRESS: 0x24EEA4,
        //   BATTLE_BACKGROUNDS_COUNT: 20,
      
        //   TRAINER_DATA_ADDRESS: 0x23EB60,
        //   TRAINER_COUNT: 742,
        //   TRAINER_SPRITE_COUNT: 148,
        //   TRAINER_BITMAPS_ADDRESS: 0x2395EC,
        //   TRAINER_PALETTES_ADDRESS: 0x239A8C,
        //   TRAINER_CLASS_NAMES: 0xD80B4,
        //   TRAINER_CLASS_COUNT: 107
        // },
        BPEE: {
          FREE_SPACE_START: 0xE3CF64,
          MONSTER_COUNT: 412,
          MONSTER_NAMES_ADDRESS: 0x144,
          MONSTER_BASE_STATS_ADDRESS: 0x1D648C,
          ABILITY_NAMES_ADDRESS: 0x031B6DB,
          ABILITY_COUNT: 78,
          MOVE_NAMES_ADDRESS: 0x148,
          MOVE_COUNT: 355,
          MONSTER_FRONT_PIXEL_ADDRESS: 0x0301418,
          MONSTER_BACK_PIXEL_ADDRESS: 0x03028B8,
          MONSTER_NORMAL_PALETTE_ADDRESS: 0x0303678,
          MONSTER_SHINY_PALETTE_ADDRESS: 0x0304438,
          MONSTER_ICON_PIXEL_ADDRESS: 0x57BCA8,
          MONSTER_ICON_PALETTE_ADDRESS: 0x57C388,
          MONSTER_ICON_PALETTES: 0xDDE1F8,
          MONSTER_ICON_PALETTE_COUNT: 3,
      
          STARTER_MONSTERS_ADDRESS: 0x5B1DF8,
          START_BANK_ID_ADDRESS: 0x054A04,
          START_MAP_ID_ADDRESS: 0x054A06,
          START_TILE_X_ADDRESS: 0x054A08,
          START_TILE_Y_ADDRESS: 0x054A00,
      
          ITEM_COUNT: 375,
          ITEM_DATA_ADDRESS: 0x05839A0,
          ITEM_BITMAPS_ADDRESS: 0x614410,
      
          MAP_ENCOUNTER_TABLE: 0xB4D48,
          MAP_NAME_OFFSET: 0,
          MAP_NAMES_ADDRESS: 0x5A0B10,
          MAP_NAMES_COUNT: 109,
          MAP_BANK_ADDRESS: 0x486578,
          MAP_BANK_COUNT: 43,
          MAP_BANK_SIZES: [57,5,5,6,7,8,9,7,7,14,8,17,10,23,13,15,15,2,2,2,3,1,1,1,108,61,89,2,1,13,1,1,2,1],
          BLOCK_BIT_SIZE: 24,
          MAIN_TILESET_BLOCK_COUNT: 512,
          MAIN_TILESET_PALETTE_COUNT: 6,
      
          MAP_TILESET_BASE: 0x3DF704,
          MAP_TILESET_ANIMATION_FLAG: 0x68014809,
          MAP_TILESET_ANIMATION_HEADER: 0x3DF718,
          MAP_SPRITES_ADDRESS: 0x505620,
          MAP_SPRITES_PALETTES: 0x50BBC8,
          MAP_DOORS_ADDRESS: 0x497174,
          MAP_DOOR_PIXEL_LENGTH: 256,
          DEFAULT_MAP: '0.9',
      
          // Credits to maierfelix for the structure
          FIELD_OVERLAY_HEADER_ADDRESS: 0x5059F8,
          FIELD_OVERLAY_META: [
            { index: 0, label: 'Shadow (small)', paletteOverrideId: 2 },
            { index: 1, label: 'Shadow (medium)', paletteOverrideId: 2 },
            { index: 2, label: 'Shadow (large)', paletteOverrideId: 2 },
            { index: 3, label: 'Shadow (extra large)', paletteOverrideId: 2 },
            { index: 4, label: 'Tall Grass' },
            { index: 5, label: 'Ripple' },
            { index: 6, label: 'Ash' },
            { index: 7, label: 'Surf Blob' },
            { index: 8, label: 'Arrow' },
            { index: 9, label: 'Ground Impact Dust' },
            { index: 10, label: 'Jump Tall Grass' },
            { index: 11, label: 'Sand Footprints' },
            { index: 12, label: 'Jump Big Splash' },
            { index: 13, label: 'Splash' },
            { index: 14, label: 'Jump Small Splash' },
            { index: 15, label: 'Long Grass' },
            { index: 16, label: 'Jump Long Grass' },
            { index: 17, label: 'Unused Grass 1' },
            { index: 18, label: 'Unused Grass 2' },
            { index: 19, label: 'Unused Sand' },
            { index: 20, label: 'Water Surfacing' },
            // { index: 21, tilemapWidth: 16, tilemapHeight: 80, label: 'Reflection Distortion' },
            { index: 22, label: 'Sparkle' },
            { index: 23, label: 'Deep Sand Footprints' },
            { index: 24, label: 'Tree Disguise', paletteOverrideId: 2 },
            { index: 25, label: 'Mountain Disguise', paletteOverrideId: 3 },
            { index: 26, label: 'Bird' },
            { index: 27, label: 'Bike Tire Tracks' },
            { index: 28, label: 'Sand Disguise', paletteOverrideId: 3 },
            { index: 29, label: 'Sand Pile' },
            { index: 30, label: 'Short Grass' },
            { index: 31, label: 'Hot Springs Water' },
            { index: 32, label: 'Ash Puff' },
            { index: 33, label: 'Ash Launch' },
            { index: 34, label: 'Bubbles' },
            { index: 35, label: 'Small Sparkle' },
            { index: 36, label: 'Rayquaza', paletteOverrideId: 2 }
          ],
          FIELD_OVERLAY_PALETTES: [
            { key: 0xFFFF, address: 0x4AD918 },
            { key: 0x1004, address: 0x4F77B8 },
            { key: 0x1005, address: 0x4F77D8 }
          ],
          FIELD_OVERLAY_BASE_OAM_ADDRESS: 0x5094ec,
          GRASS_OVERLAY_PIXEL_ADDRESS: 0x39a048,
          GRASS_OVERLAY_PALETTE_ADDRESS: 0x398FC8,
      
          MUSIC_MODIFIER: 352,
          MUSIC_NAMES: ["???", "GS - Route 38", "Wild Pokemon Defeat", "Wild Pokemon Defeat w/Intro", "Gym Leader Defeat", "Acquired Badge", "Crystal - Pokémon Center", "GS - Saffron City", "Crystal - Battle with Legendary Dogs", "Route Theme 1", "Route Theme 2", "Route Theme 3", "Petalburg City", "Gym", "Surfing", "Level Up", "Pokemon Healed", "Big Victory", "Acquired Item", "Pokemon Caught", "Got TM/HM", "Lilycove Museum", "Route Theme 4", "Slateport Museum", "Evolve Intro", "Evolving", "Unknown Victory 1", "Tuber Encounter", "Boy Encounter", "A Far-away Place", "Fortree City", "Birch's Lab", "Battle Tower", "Swimmer Encounter", "Meteor Falls", "Got a Berry", "Unknown Victory 1", "Unknown Victory 3", "Unknown Victory 4", "Pay No Attention!", "Unknown Theme 1", "Beauty Contest Test 1", "Beauty Contest Test 2", "Beauty Contest Test 3", "Beauty Contest Test 4", "Ship Encounter", "Verdanturf Town", "Rustboro City", "Pokémon Center", "Route Theme 5", "Route Theme 6", "Bicycle Ride", "PokéMart", "Littleroot Town", "Sky Pillar", "Girl Encounter", "Lilycove City", "The Sandy Desert", "Help Me!", "Underwater Dive", "Trainer Defeat", "Title Screen", "Introduction", "May's Theme", "Electric Encounter", "Biker Encounter", "Route Theme 7", "Aqua Encounter", "Show Me Around", "Brendan's Theme", "Evergrande City", "Psychic Encounter", "Important Defeat", "Riding the Cable Car", "Game Corner", "Dewford Town", "Safari Zone", "Victory Road", "Team Hideout", "Sailing the Sea", "Shoal Cave", "Slateport City", "The Fog of Mt. Pyre", "Pokémon Trainer School", "You're the Champ!", "Lavaridge Town", "Island Cave", "Important 2 Defeat", "Beauty Contest", "Magma Encounter", "The Pokémon!", "The Flood", "The Drought", "Sootopolis City", "Berry Blending Results", "Hall of Fame", "You're Being Watched!", "Kid Encounter", "Elite Four Theme", "Sailor Encounter", "Beauty Contest Lobby", "What's On TV?", "Unknown Encounter", "Ending Credits", "The End!", "Battle Frontier", "Battle Arena", "Battle Point!", "Registered Trainer", "Battle Pyramid", "Pyramid Top", "Battle Palace", "Rayquaza Enters", "Battle Tower", "Frontier Badge!", "Dome Tournament", "Battle Tube", "Battle Factory", "Battle - Legendary Pokémon", "Battle - Frontier Brains", "Battle - Mew", "Battle Dome Lobby", "Battle - Wild Pokémon", "Battle - Aqua/Magma", "Battle - Pokémon Trainer", "Battle - Gym Leader", "Battle - Champion Wallace", "Battle - Regirock, Regice and Registeel", "Battle - Legendary Pokémon", "Battle - Rival", "Battle - Elite Four", "Battle - Team Leader", "Follow Me", "Game Corner", "Evil Lurks", "Gym(FRLG)", "Jigglypuff's Song ", "Introduction (FRLG)", "Pokémon Theme", "Cinnabar Island", "Lavender Town", "Healing", "Bicycle", "Encounter 1", "Encounter 2", "Encounter 3", "You're in the Hall Of Fame!", "Viridian Forest", "Mount Moon", "Abandoned Place", "End Credits (FRLG)", "Route Theme 8", "Route Theme 9 (FRLG Intro)", "Route Theme 10", "Route Theme 11", "Indigo Plateau", "Battle 3", "Battle 4", "Battle 5", "Battle 6", "Pallet Town", "Oak's Lab", "Oak's Theme", "Pokémon Center", "SS Anne", "Surf's Up", "Pokémon Tower", "Silph Co.", "Cerulean City", "Celadon City", "Victory 1", "Victory 2", "Victory 3", "Vermillion City", "Viridian City", "Gary's Theme", "Gary's Theme (bis)", "Fanfare 3", "Fanfare 4", "You caught a Pokémon!", "Trainer Card Photo", "Gamefreak", "Victory 2 (bis)", "Intro Message 1", "Intro Message 2", "Intro Message 3", "Game Corner (+1)", "Game Corner (+2)", "Net Center", "Mystery Connection", "Game Corner (+3)", "Mount Ember", "Follow Me (alt)", "Sevii Island Paths", "Tanoby Ruins", "Islands 1-3", "Islands 4-5", "Islands 6-7", "PokéFlute", "Battle - Deoxys", "Battle 5 (+1)", "Battle 5 (+2)", "Encounter 4", "Deoxys Encounter", "Trainer Tower", "Pallet Town (fame mix)", "Teachy TV"],
      
          BATTLE_BACKGROUNDS_ADDRESS: 0x31ABA8,
          BATTLE_BACKGROUNDS_COUNT: 10,
      
          TRAINER_DATA_ADDRESS: 0x310030,
          TRAINER_COUNT: 742,
          TRAINER_SPRITE_COUNT: 93,
          TRAINER_BITMAPS_ADDRESS: 0x305654,
          TRAINER_PALETTES_ADDRESS: 0x30593C,
          TRAINER_CLASS_NAMES: 0x183B4,
          TRAINER_CLASS_COUNT: 66
        }
    }
}